### ISSUE TITLE
Reading video file halts after a while

### ISSUE THREAD

**Issue by serser** [kanryu/pipeffmpeg#3]
After installed, I found it can't manage larger files, it will generally suspend reading after reading 1k frames.

    import pipeffmpeg

    vid = pipeffmpeg.InputVideoStream()
    vid.open("A Long Video.mp4")

    for i, img in enumerate(vid.readframe()):
        print i

**Comment by kanryu** [comment]
OK, I've checked.

but that problem is a commonly problem about subprocess.pipe
e.g. if we read many time from subprocess.pipe.stdout, that will locked.

If you know goot:answer for that, please reply here :)

**Comment by kanryu** [comment]
I'd fixed.

You can check it :)
